name: 💡 Category Request
description: Suggest an category for this document.
labels: [enhancement]

body:
  - type: textarea
    attributes:
      label: Idea
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the request here.
    validations:
      required: false
